
cloud:
  aws:
    region:
      auto: false
      static: us-east-1
      use-default-aws-region-chain: true
    stack: false
    stack.auto: false
    credentials:
      access-key: AKIARJ5IXUPURLJ7WEGX
      secret-key: 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
logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error